import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/navbar'
import Temas from '@/components/temas'
import imagenDesarollador from '/src/static/images/diseno-de-paginas-web.png'
import FoterMain from '@/components/foterMain'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Codigo Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={`${styles.containerIndex} `}>
        <NavBar title="Codigo de la Web" />
        <main>
          <h1>
            Encuentra en nuestra página los enlaces que necesitas para guiarte en la programación web.
          </h1>
        </main>
        <aside>
          <input type="search" id="search" name="search" />
        </aside>
        <span>
          <Image
            width={350}
            src={imagenDesarollador} 
            alt="diseno-de-paginas-web" 
          />
        </span>
        <Temas />
        {/*<FoterMain />*/}
      </div>
    </>
  )
}
